# Base image
ARG BASE_IMAGE_VERSION

FROM registry.docker.libis.be/teneo/ruby-base:${BASE_IMAGE_VERSION}

# Install some Rails requirements NodeJS and yarn
RUN apt-get update -qq \
    && apt-get install -qqy --no-install-recommends \
        nodejs \
        npm \
    && apt-get clean \
    && rm -fr /var/cache/apt/archives/* \
    && rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp* \
    && truncate -s 0 /var/log/*log
RUN npm install -g yarn

# Prepare ruby environment
ENV RAILS_ENV=production
